
server:
  port: 8020

spring:
  application:
    name: yangyu-1-user
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    data: classpath:data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/