server:
  port: 8008
spring:
  profiles:
      active: dev
  cloud:
      config:
        server:
          native:
            search-locations: file:///D:/java/idea_workspace/yangyu/yangyu-0-config/src/main/resources/config #配置文件根目录
security: #加密配置
  user:
    name: config
    password: admin
management:
  security:
    enabled: false