server:
  port: 8008
spring:
  profiles:
      active: native
  cloud:
      config:
        server:
          native:
            search-locations: classpath:/config #配置文件根目录
security: #加密配置
  user:
    name: config
    password: admin
management:
  security:
    enabled: false