server:
  port: 8021
spring:
  application:
    name: yangyu-2-news
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/yangyu?useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    elasticsearch:
      cluster-name: youz
      cluster-nodes: 119.23.13.226:9300
      local: false
      repositories:
          enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
