server:
  port: 8095

spring:
  mail:
    host: smtp.163.com
    username: yz7276@163.com
    password: y12345
  cloud:
   stream:
    kafka:
      binder:
        brokers: localhost:9092
        zk-nodes: localhost:2181
        auto-add-partitions: true
        auto-create-topics: true
        min-partition-count: 1
    bindings:
      input:
        destination: yangyu-email
        group: s1
        consumer:
          autoCommitOffset: false
          concurrency: 1
          partitioned: false
