eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 2 #契约更新间隔
    lease-expiration-duration-in-seconds: 4 #契约过期时间
    preferIpAddress: true

server:
  port: 8090

feign:
  hystrix:
    enabled: false

security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin

jwt:
  expirationTime: 86400000
  tokenHeader: Authorization
  tokenPrefix: Bearer
  secret:
    key: admin