eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 2 #契约更新间隔
    lease-expiration-duration-in-seconds: 4 #契约过期时间
    preferIpAddress: true

server:
  port: 8021

spring:
  application:
    name: yangyu-2-news
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/yangyu?useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

yangyu:
  elasticsearch:
    host: 192.168.99.100
    port: 9300