server:
  port: 8090

feign:
  hystrix:
    enabled: false

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.84.128:9092
          zk-nodes: 192.168.84.128:2181
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
      bindings:
        output:
          destination: yangyu-email
          content-type: application/json
          producer:
            partitionCount: 1

security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin

jwt:
  expirationTime: 86400000
  tokenHeader: Authorization
  tokenPrefix: Bearer
  secret:
    key: admin