server:
  port: 8020

spring:
  datasource:
    url: jdbc:mysql://192.168.67.128:3306/yangyu?useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    data: classpath:data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update