spring:
  cloud:
   instance-count: 1
   instance-index: 0
   stream:
    kafka:
      binder:
        brokers: localhost:9092
        zk-nodes: localhost:2181
        auto-add-partitions: true
        auto-create-topics: true
        min-partition-count: 1
    bindings:
      input:
        destination: yangyu-email
        group: s1
        consumer:
          autoCommitOffset: false
          concurrency: 1
          partitioned: false