yangyu:
  jwt:
    tokenPrefix: Bearer
    tokenHeader: Authorization
    secretKey: youz
    issuer: http://youz.yangyu.com
    expirationTime: 86400000 #超时时间 60 * 60 * 24 * 1000

server:
  port: 8020

spring:
  application:
    name: yangyu-1-user
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin

