
server:
  port: 8020

spring:
  application:
    name: yangyu-1-user
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/yangyu?useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    data: classpath:data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/