spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.99.100:9092
          zkNodes: 192.168.99.100:2181
          replicationFactor: 3
      bindings:
        topic_out:
          destination: test
          partitionCount: 2
  application:
    name: yangyu-study-stream-provider
server:
  port: 8081
