spring:
  application:
    name: yangyu-study-stream-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
      bindings:
        input:
          destination: event-demo
          group: s1
          consumer:
            autoCommitOffset: false
            concurrency: 1
            partitioned: false
server:
  port: 8082
