spring:
  application:
    name: yangyu-study-stream-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.99.100:9092
          zkNodes: 192.168.99.100:2181
          replicationFactor: 3
      bindings:
        topic_in:
          destination: test
          group: group
          consumer:
            maxAttempts: 1
            partitioned: true
server:
  port: 8082
