spring:
  application:
    name: yangyu-message
  cloud:
     instance-count: 1
     instance-index: 0
     stream:
        kafka:
          binder:
            brokers: 192.168.99.100:9092
            zk-nodes: 192.168.99.100:2182
            auto-add-partitions: true
            auto-create-topics: true
            min-partition-count: 1
        bindings:
          input:
            destination: yangyu-demo
            group: s3
            consumer:
              autoCommitOffset: false
              concurrency: 1
              partitioned: false
