online: false

server:
  port: 8020
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: yangyu-news-user-server
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

