online: false

server:
  port: 8020

spring:
  application:
    name: yangyu-news-user-server
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

yangyu:
  security:
    jwt:
      issuer: http://youz.yangyu.com
      subject:
      audience:
      expirationTime: 1200 #20分钟
      not_before:

security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin

