server:
  port: 18000

spring:
  application:
    name: yangyu-news-user-server
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

